(function () {
  if (
    typeof window != "undefined" &&
    window.location &&
    window.location.protocol !== "file:" &&
    !/^https?:\/\/(.*\.)?(redo-san\.github\.io|localhost|127\.0\.0\.1)(:\d+)?(\/|$)/.test(
      window.location.href,
    )
  )
    throw new Error(
      "RedoSan Authenticity: This script is protected by GPL license.",
    );
})();
// ── EPUB Certificate Generator ──

/**
 *
 * @param data
 */
async function downloadCertEPUB(data) {
  var qrText = buildQRVerificationJSON(data);
  var docHash = await getDocHash(qrText);
  var qrContent = JSON.stringify({ data: JSON.parse(qrText), hash: docHash });
  var qrDataUrl = generateQRDataURL(qrContent, 400);

  var imgBase64 = "";
  if (data.file.dataUrl) {
    imgBase64 = data.file.dataUrl.split(",", 2)[1];
  }
  var qrBase64 = qrDataUrl.split(",", 2)[1];
  var imgMime = data.file.type || "image/png";

  // Build HTML content
  var userSection = "";
  if (data.user.name) {
    userSection += "<h2>Owner</h2><table>";
    if (data.user.name)
      userSection +=
        "<tr><td><strong>Name</strong></td><td>" +
        escHtml(data.user.name) +
        "</td></tr>";
    if (data.user.email)
      userSection +=
        "<tr><td><strong>Email</strong></td><td>" +
        escHtml(data.user.email) +
        "</td></tr>";
    if (data.user.phone)
      userSection +=
        "<tr><td><strong>Phone</strong></td><td>" +
        escHtml(data.user.phone) +
        "</td></tr>";
    if (data.user.website)
      userSection +=
        "<tr><td><strong>Website</strong></td><td>" +
        escHtml(data.user.website) +
        "</td></tr>";
    userSection += "</table>";
  }

  var fpSection = "";
  if (data.fingerprint && data.fpResult && data.fpResult.hashes) {
    fpSection += "<h2>Fingerprint (Hashes)</h2>";
    var families = [
      { label: "SHA-1", keys: ["SHA-1"] },
      { label: "SHA-2", keys: ["SHA-224", "SHA-256", "SHA-384", "SHA-512"] },
      {
        label: "SHA-3",
        keys: ["SHA-3_224", "SHA-3_256", "SHA-3_384", "SHA-3_512"],
      },
      { label: "MD", keys: ["MD2", "MD4", "MD5"] },
      { label: "BLAKE", keys: ["BLAKE2b", "BLAKE2s", "BLAKE3"] },
      { label: "Other", keys: ["RIPEMD-160", "Whirlpool"] },
    ];
    for (var fi = 0; fi < families.length; fi++) {
      var fam = families[fi];
      var has = false;
      for (var ki = 0; ki < fam.keys.length; ki++) {
        if (data.fpResult.hashes[fam.keys[ki]]) {
          has = true;
          break;
        }
      }
      if (!has) continue;
      fpSection += "<h3>" + escHtml(fam.label) + "</h3><table>";
      for (ki = 0; ki < fam.keys.length; ki++) {
        var v = data.fpResult.hashes[fam.keys[ki]];
        if (v)
          fpSection +=
            "<tr><td><strong>" +
            escHtml(fam.keys[ki]) +
            '</strong></td><td style="font-size:0.7em;word-break:break-all">' +
            escHtml(v) +
            "</td></tr>";
      }
      fpSection += "</table>";
      await new Promise(function (r) {
        setTimeout(r, 0);
      });
    }
    if (data.fpResult.perceptual_hashes) {
      for (var pk in data.fpResult.perceptual_hashes) {
        fpSection +=
          "<h3>" +
          escHtml(pk) +
          '</h3><p style="font-size:0.7em;word-break:break-all">' +
          escHtml(data.fpResult.perceptual_hashes[pk]) +
          "</p>";
      }
    }
  }

  var xhtml =
    '<?xml version="1.0" encoding="UTF-8"?>' +
    "<!DOCTYPE html>" +
    '<html xmlns="http://www.w3.org/1999/xhtml">' +
    '<head><meta charset="utf-8"/><title>Digital Passport</title>' +
    '<link rel="stylesheet" type="text/css" href="style.css"/>' +
    "</head><body>" +
    "<h1>Digital Passport</h1>" +
    '<p class="subtitle">Generated by RedoSan Authenticity — ' +
    escHtml(data.generatedAt.replace("T", " ").substring(0, 19)) +
    "</p>" +
    userSection +
    "<h2>File Information</h2>" +
    "<table>" +
    "<tr><td><strong>Name</strong></td><td>" +
    escHtml(data.file.name) +
    "</td></tr>" +
    "<tr><td><strong>Size</strong></td><td>" +
    fmtSize(data.file.size) +
    "</td></tr>" +
    (data.file.width
      ? "<tr><td><strong>Dimensions</strong></td><td>" +
        data.file.width +
        " x " +
        data.file.height +
        " px</td></tr>"
      : "") +
    (data.file.hash
      ? '<tr><td><strong>SHA-256</strong></td><td style="font-size:0.7em;word-break:break-all">' +
        data.file.hash +
        "</td></tr>"
      : "") +
    "</table>" +
    (imgBase64
      ? '<div class="img-wrapper"><img src="images/photo.' +
        (data.file.type === "image/png" ? "png" : "jpg") +
        '" alt="Original Image"/></div>'
      : "") +
    (data.watermark
      ? "<h2>Watermark</h2><p><strong>Result:</strong> " +
        escHtml(data.watermarkAlgo || "Completed") +
        "</p><pre>" +
        escHtml(data.watermarkResult || "") +
        "</pre>"
      : "") +
    (data.documentWatermark
      ? "<h2>Document Watermark</h2><p><strong>File:</strong> " +
        escHtml(data.documentWatermarkFileName || "Completed") +
        "</p><pre>" +
        escHtml(data.documentWatermarkResult || "") +
        "</pre>"
      : "") +
    (data.pixelInjection
      ? "<h2>Pixel Injection</h2><p><strong>Result:</strong> Completed</p><pre>" +
        escHtml(data.piResultHtml || "") +
        "</pre>"
      : "") +
    (data.timestamp
      ? "<h2>Timestamp</h2><pre>" +
        escHtml(data.tsResult || "Timestamp created successfully.") +
        "</pre>"
      : "") +
    fpSection +
    (data.didSig && data.didSig.did
      ? "<h2>Decentralized Identity (DID)</h2><table>" +
        '<tr><td><strong>DID</strong></td><td style="font-size:0.7em;word-break:break-all">' +
        escHtml(data.didSig.did) +
        "</td></tr>" +
        "<tr><td><strong>Algorithm</strong></td><td>" +
        escHtml(data.didSig.algorithm || "Ed25519") +
        "</td></tr>" +
        "<tr><td><strong>Signed</strong></td><td>" +
        escHtml(
          (data.didSig.timestamp || "").replace("T", " ").substring(0, 19),
        ) +
        "</td></tr>" +
        '<tr><td><strong>Signature</strong></td><td style="font-size:0.6em;word-break:break-all">' +
        escHtml((data.didSig.signature || "").substring(0, 64) + "...") +
        "</td></tr></table>"
      : data.didIdentity
      ? '<h2>DID Identity</h2><table><tr><td><strong>DID</strong></td><td style="font-size:0.7em;word-break:break-all">' +
        escHtml(data.didIdentity) +
        "</td></tr></table>"
      : "") +
    (data.ct && data.ct.submitted && data.ct.hash
      ? "<h2>Certificate Transparency</h2><table>" +
        '<tr><td><strong>SHA-256</strong></td><td style="font-size:0.6em;word-break:break-all">' +
        escHtml(data.ct.hash) +
        "</td></tr>" +
        (data.ct.pending
          ? ""
          : "<tr><td><strong>Logged</strong></td><td>" +
            escHtml(
              (data.ct.timestamp || "").replace("T", " ").substring(0, 19),
            ) +
            "</td></tr>" +
            "<tr><td><strong>Log</strong></td><td>" +
            escHtml(
              (data.ct.aggregator || "OTS")
                .replace("https://", "")
                .split("/", 1)[0] || "OTS calendar",
            ) +
            "</td></tr>") +
        '</table><p>Verifiable at: <a href="https://opentimestamps.org">opentimestamps.org</a></p>'
      : data.ct
      ? "<h2>Certificate Transparency</h2><p>Status: " +
        escHtml(
          data.ct.submitted
            ? "Submitted"
            : "Unavailable — " + (data.ct.error || "offline"),
        ) +
        "</p>"
      : "") +
    "<h2>Verification QR Code</h2>" +
    "<p>Scan this QR code to verify the document contents.</p>" +
    '<div class="qr-wrapper"><img src="images/qr.png" alt="QR Code"/></div>' +
    '<pre class="qr-data">' +
    escHtml(qrContent) +
    "</pre>" +
    "</body></html>";

  var css =
    "body{font-family:serif;padding:20px;max-width:800px;margin:0 auto}" +
    "h1{font-size:1.6em;border-bottom:2px solid #333;padding-bottom:8px}" +
    ".subtitle{color:#666;font-size:0.85em}" +
    "h2{font-size:1.2em;margin-top:24px;border-bottom:1px solid #ccc;padding-bottom:4px}" +
    "h3{font-size:1em;margin-top:16px}" +
    "table{width:100%;border-collapse:collapse;margin:8px 0}" +
    "td{padding:4px 8px;border:1px solid #ddd;vertical-align:top;font-size:0.85em}" +
    "td:first-child{white-space:nowrap;font-weight:700;width:120px}" +
    ".img-wrapper{text-align:center;margin:16px 0}" +
    ".img-wrapper img{max-width:100%;max-height:400px}" +
    ".qr-wrapper{text-align:center;margin:16px 0}" +
    ".qr-wrapper img{width:200px;height:200px}" +
    ".qr-data{font-size:0.6em;background:#f5f5f5;padding:8px;border:1px solid #ddd;white-space:pre-wrap;word-break:break-all}";

  // Generate EPUB zip
  var zip = new JSZip();
  zip.file("mimetype", "application/epub+zip", { compression: "STORE" });
  zip
    .folder("META-INF")
    .file(
      "container.xml",
      '<?xml version="1.0" encoding="UTF-8"?>' +
        '<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">' +
        '<rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>',
    );

  var manifestItems = [
    { id: "content", href: "content.xhtml", mt: "application/xhtml+xml" },
    { id: "style", href: "style.css", mt: "text/css" },
    { id: "ncx", href: "toc.ncx", mt: "application/x-dtbncx+xml" },
  ];
  if (data.file.dataUrl) {
    var imgExt = data.file.type === "image/png" ? "png" : "jpg";
    manifestItems.push({
      id: "img",
      href: "images/photo." + imgExt,
      mt: data.file.type || "image/jpeg",
    });
  }
  manifestItems.push({ id: "qr", href: "images/qr.png", mt: "image/png" });

  var spineItems = manifestItems.filter(function (m) {
    return m.mt === "application/xhtml+xml";
  });

  var ncx =
    '<?xml version="1.0" encoding="UTF-8"?>' +
    '<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">' +
    '<head><meta name="dtb:uid" content="urn:uuid:' +
    makeUUID() +
    '"/></head>' +
    "<docTitle><text>Digital Passport</text></docTitle>" +
    '<navMap><navPoint id="np-1" playOrder="1">' +
    "<navLabel><text>Digital Passport</text></navLabel>" +
    '<content src="content.xhtml"/>' +
    "</navPoint></navMap></ncx>";

  var opf =
    '<?xml version="1.0" encoding="UTF-8"?>' +
    '<package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="uid">' +
    '<metadata><dc:identifier xmlns:dc="http://purl.org/dc/elements/1.1/" id="uid">' +
    "urn:uuid:" +
    makeUUID() +
    "</dc:identifier>" +
    '<dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">Digital Passport</dc:title>' +
    '<dc:language xmlns:dc="http://purl.org/dc/elements/1.1/">en</dc:language>' +
    '<dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">RedoSan Authenticity</dc:creator>' +
    "</metadata><manifest>";
  for (var mi = 0; mi < manifestItems.length; mi++) {
    opf +=
      '<item id="' +
      manifestItems[mi].id +
      '" href="' +
      manifestItems[mi].href +
      '" media-type="' +
      manifestItems[mi].mt +
      '"/>';
  }
  opf += '</manifest><spine toc="ncx">';
  for (var si = 0; si < spineItems.length; si++) {
    opf += '<itemref idref="' + spineItems[si].id + '"/>';
  }
  opf += "</spine></package>";

  zip.folder("OEBPS").file("content.opf", opf);
  zip.folder("OEBPS").file("content.xhtml", xhtml);
  zip.folder("OEBPS").file("style.css", css);
  zip.folder("OEBPS").file("toc.ncx", ncx);
  if (data.file.dataUrl) {
    var imgExt = data.file.type === "image/png" ? "png" : "jpg";
    zip
      .folder("OEBPS")
      .folder("images")
      .file("photo." + imgExt, imgBase64, { base64: true });
  }
  zip
    .folder("OEBPS")
    .folder("images")
    .file("qr.png", qrBase64, { base64: true });

  await new Promise(function (r) {
    setTimeout(r, 0);
  });
  var blob = await zip.generateAsync({ type: "blob" });
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url;
  a.download = "RedoSan_Digital_Passport.epub";
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(function () {
    URL.revokeObjectURL(url);
  }, 1000);
  return blob;
}
