(function () {
  if (
    typeof window != "undefined" &&
    window.location &&
    window.location.protocol !== "file:" &&
    !/^https?:\/\/(.*\.)?(redo-san\.github\.io|localhost|127\.0\.0\.1)(:\d+)?(\/|$)/.test(
      window.location.href,
    )
  )
    throw new Error(
      "RedoSan Authenticity: This script is protected by GPL license.",
    );
})();
// ── PDF Certificate Generator ──

/**
 *
 * @param data
 */
async function downloadCertPDF(data) {
  var doc = new jspdf.jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });
  var pw = 210,
    ph = 297,
    margin = 15,
    y = margin;
  var pageW = pw - 2 * margin;
  var img,
    dims,
    imgW,
    imgH,
    qrDataUrl,
    qrSize = 50;

  // Load image (only for actual images)
  if (data.file.dataUrl && data.file.width && data.file.height) {
    img = data.file.dataUrl;
    dims = { w: data.file.width, h: data.file.height };
    imgW = pageW;
    imgH = (imgW * dims.h) / dims.w;
    if (imgH > 120) {
      imgH = 120;
      imgW = (imgH * dims.w) / dims.h;
    }
  }

  // Generate QR
  var qrVerData = buildQRVerificationJSON(data);
  var docHash = await getDocHash(qrVerData);
  var qrContent = JSON.stringify({
    data: JSON.parse(qrVerData),
    hash: docHash,
  });
  qrDataUrl = generateQRDataURL(qrContent, 400);

  /**
   *
   * @param need
   */
  function checkPage(need) {
    if (y + need > ph - margin) {
      doc.addPage();
      y = margin;
    }
  }

  // Title
  doc.setFontSize(18);
  doc.text("Digital Passport", pw / 2, y, { align: "center" });
  y += 10;
  doc.setFontSize(8);
  doc.text(
    "Generated by RedoSan Authenticity — " +
      data.generatedAt.replace("T", " ").substring(0, 19),
    pw / 2,
    y,
    { align: "center" },
  );
  y += 8;

  // ── 1. User Info ──
  if (data.user.name) {
    checkPage(12);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Owner", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(9);
    if (data.user.name) {
      addTextSafe(doc, "Name: " + data.user.name, margin, y, pageW, 9);
      y += 4;
    }
    if (data.user.email) {
      addTextSafe(doc, "Email: " + data.user.email, margin, y, pageW, 9);
      y += 4;
    }
    if (data.user.phone) {
      addTextSafe(doc, "Phone: " + data.user.phone, margin, y, pageW, 9);
      y += 4;
    }
    if (data.user.website) {
      addTextSafe(doc, "Website: " + data.user.website, margin, y, pageW, 9);
      y += 4;
    }
    y += 2;
  }

  // ── 2. File Info ──
  checkPage(20);
  doc.setFontSize(12);
  doc.setFont(undefined, "bold");
  doc.text("File Information", margin, y);
  y += 5;
  doc.setFont(undefined, "normal");
  doc.setFontSize(9);
  addTextSafe(doc, "Name: " + data.file.name, margin, y, pageW, 9);
  y += 4;
  doc.text("Size: " + fmtSize(data.file.size), margin, y);
  y += 4;
  if (data.file.width)
    doc.text(
      "Dimensions: " + data.file.width + " x " + data.file.height + " px",
      margin,
      y,
    );
  y += data.file.width ? 4 : 0;
  if (data.file.hash) doc.text("SHA-256: " + data.file.hash, margin, y);
  y += data.file.hash ? 4 : 0;
  y += 2;

  // Embed image
  if (img) {
    checkPage(imgH + 8);
    var imgFmt = data.file.type === "image/png" ? "PNG" : "JPEG";
    doc.addImage(img, imgFmt, (pw - imgW) / 2, y, imgW, imgH);
    y += imgH + 6;
  }

  // ── 3. Watermark ──
  if (data.watermark) {
    checkPage(12);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Watermark", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(9);
    doc.text("Result: " + (data.watermarkAlgo || "Completed"), margin, y);
    y += 4;
    if (data.watermarkResult) {
      doc.setFontSize(7);
      var wmLines = doc.splitTextToSize(data.watermarkResult, pageW);
      doc.text(wmLines, margin, y);
      y += wmLines.length * 3.5;
    }
    y += 2;
  }

  // ── 3b. Document Watermark ──
  if (data.documentWatermark) {
    checkPage(12);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Document Watermark", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(9);
    doc.text(
      "File: " + (data.documentWatermarkFileName || "Completed"),
      margin,
      y,
    );
    y += 4;
    if (data.documentWatermarkResult) {
      doc.setFontSize(7);
      var docwLines = doc.splitTextToSize(data.documentWatermarkResult, pageW);
      doc.text(docwLines, margin, y);
      y += docwLines.length * 3.5;
    }
    y += 2;
  }

  // ── 4. Pixel Injection ──
  if (data.pixelInjection) {
    checkPage(12);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Pixel Injection", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(9);
    doc.text("Result: Completed", margin, y);
    y += 4;
    if (data.piResultHtml) {
      doc.setFontSize(7);
      var piLines = doc.splitTextToSize(data.piResultHtml, pageW);
      doc.text(piLines, margin, y);
      y += piLines.length * 3.5;
    }
    y += 2;
  }

  // ── 5. Timestamp ──
  if (data.timestamp) {
    checkPage(12);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Timestamp", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(9);
    if (data.tsResult) {
      var tsLines = doc.splitTextToSize(data.tsResult, pageW);
      doc.text(tsLines, margin, y);
      y += tsLines.length * 3.5;
    } else {
      doc.text("Timestamp created successfully.", margin, y);
      y += 4;
    }
    y += 2;
  }

  // ── 6. Fingerprint (hashes) ──
  if (data.fingerprint && data.fpResult && data.fpResult.hashes) {
    checkPage(16);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Fingerprint (Hashes)", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(7);
    var families = [
      { label: "SHA-1", keys: ["SHA-1"] },
      { label: "SHA-2", keys: ["SHA-224", "SHA-256", "SHA-384", "SHA-512"] },
      {
        label: "SHA-3",
        keys: ["SHA-3_224", "SHA-3_256", "SHA-3_384", "SHA-3_512"],
      },
      { label: "MD", keys: ["MD2", "MD4", "MD5"] },
      { label: "BLAKE", keys: ["BLAKE2b", "BLAKE2s", "BLAKE3"] },
      { label: "Other", keys: ["RIPEMD-160", "Whirlpool"] },
    ];
    for (var fi = 0; fi < families.length; fi++) {
      var fam = families[fi];
      var has = false;
      for (var ki = 0; ki < fam.keys.length; ki++) {
        if (data.fpResult.hashes[fam.keys[ki]]) {
          has = true;
          break;
        }
      }
      if (!has) continue;
      checkPage(4 + fam.keys.length * 3.5);
      doc.setFont(undefined, "bold");
      doc.text(fam.label, margin, y);
      y += 3.5;
      doc.setFont(undefined, "normal");
      for (ki = 0; ki < fam.keys.length; ki++) {
        var v = data.fpResult.hashes[fam.keys[ki]];
        if (v) {
          doc.text(fam.keys[ki] + ":  " + v, margin, y);
          y += 3.5;
        }
      }
      y += 1;
      await new Promise(function (r) {
        setTimeout(r, 0);
      });
    }
    // Perceptual hashes
    if (data.fpResult.perceptual_hashes) {
      for (var pk in data.fpResult.perceptual_hashes) {
        checkPage(6);
        doc.setFont(undefined, "bold");
        doc.text(pk, margin, y);
        y += 3.5;
        doc.setFont(undefined, "normal");
        doc.text(data.fpResult.perceptual_hashes[pk], margin, y);
        y += 4;
      }
    }
  }

  // ── 7. DID Signature ──
  if (data.didSig && data.didSig.did) {
    checkPage(20);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Decentralized Identity (DID)", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(7);
    doc.text("DID: " + data.didSig.did, margin, y);
    y += 3.5;
    doc.text("Algorithm: " + (data.didSig.algorithm || "Ed25519"), margin, y);
    y += 3.5;
    doc.text(
      "Signed: " +
        (data.didSig.timestamp || "").replace("T", " ").substring(0, 19),
      margin,
      y,
    );
    y += 3.5;
    doc.setFontSize(6);
    var sigLines = doc.splitTextToSize(
      "Signature: " + (data.didSig.signature || ""),
      pageW,
    );
    doc.text(sigLines, margin, y);
    y += sigLines.length * 3 + 4;
  } else if (data.didIdentity) {
    checkPage(10);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("DID Identity", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(7);
    doc.text("DID: " + data.didIdentity, margin, y);
    y += 4;
  }

  // ── 7b. Face Biometric ──
  if (data.faceBiometric && data.faceBiometric.detected) {
    checkPage(12);
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("Face Biometric", margin, y);
    y += 5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(7);
    doc.text("Faces detected: " + data.faceBiometric.faceCount, margin, y);
    y += 4;
    if (data.faceBiometric.matchLabel) {
      doc.text("Match: " + data.faceBiometric.matchLabel, margin, y);
      y += 4;
    }
    if (data.faceBiometric.didSigned) {
      doc.text("DID Signed: Yes", margin, y);
      y += 4;
    }
    if (data.faceBiometric.did) {
      doc.text("DID: " + data.faceBiometric.did.substring(0, 60) + "...", margin, y);
      y += 4;
    }
    doc.text("Exported: " + data.faceBiometric.exportedAt, margin, y);
    y += 4;
  }

  // ── 8. Certificate Transparency ──
  if (data.ct && data.ct.submitted && data.ct.hash) {
    checkPage(12);
    doc.setFontSize(10);
    doc.setFont(undefined, "bold");
    doc.text("Certificate Transparency", margin, y);
    y += 4.5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(6);
    doc.text("SHA-256: " + data.ct.hash, margin, y);
    y += 3;
    if (data.ct.pending) {
      // hash only, no status text
    } else {
      doc.text(
        "Logged: " +
          (data.ct.timestamp || "").replace("T", " ").substring(0, 19),
        margin,
        y,
      );
      y += 3;
      var shortAgg =
        (data.ct.aggregator || "").replace("https://", "").split("/", 1)[0] ||
        "OTS calendar";
      doc.text("Transparency log: " + shortAgg, margin, y);
      y += 3;
    }
    doc.text("Verifiable at: https://opentimestamps.org", margin, y);
    y += 6;
  } else if (data.ct) {
    checkPage(8);
    doc.setFontSize(10);
    doc.setFont(undefined, "bold");
    doc.text("Certificate Transparency", margin, y);
    y += 4.5;
    doc.setFont(undefined, "normal");
    doc.setFontSize(6);
    doc.text(
      "Status: " +
        (data.ct.submitted
          ? "Submitted"
          : "Unavailable — " + (data.ct.error || "offline")),
      margin,
      y,
    );
    y += 4;
  }

  // ── 9. QR Verification Code ──
  checkPage(qrSize + 20);
  y += 4;
  doc.setFontSize(12);
  doc.setFont(undefined, "bold");
  doc.text("Verification QR Code", pw / 2, y, { align: "center" });
  y += 6;
  doc.setFont(undefined, "normal");
  doc.setFontSize(7);
  doc.text(
    "Scan this QR code to verify the document contents. The QR encodes all",
    pw / 2,
    y,
    { align: "center" },
  );
  y += 3;
  doc.text(
    "verification data (hashes, file info, owner). Compare values with those above.",
    pw / 2,
    y,
    { align: "center" },
  );
  y += 3;
  doc.text("Any mismatch indicates tampering.", pw / 2, y, { align: "center" });
  y += 6;
  doc.addImage(qrDataUrl, "PNG", (pw - qrSize) / 2, y, qrSize, qrSize);
  y += qrSize + 4;
  // QR text below
  doc.setFontSize(6);
  var lines = doc.splitTextToSize(qrContent, pageW);
  doc.text(lines, margin, y);

  await new Promise(function (r) {
    setTimeout(r, 0);
  });
  var blob = doc.output("blob");
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url;
  a.download = "RedoSan_Digital_Passport.pdf";
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(function () {
    URL.revokeObjectURL(url);
  }, 1000);
  return blob;
}
