(function () {
  if (
    typeof window != "undefined" &&
    window.location &&
    window.location.protocol !== "file:" &&
    !/^https?:\/\/(.*\.)?(redo-san\.github\.io|localhost|127\.0\.0\.1)(:\d+)?(\/|$)/.test(
      window.location.href,
    )
  )
    throw new Error(
      "RedoSan Authenticity: This script is protected by GPL license.",
    );
})();
// ── DOCX Certificate Generator ──

async function downloadCertDOCX(data) {
  var children = [];

  // Helper: convert data URL to Uint8Array
  function dataURLToUint8Array(dataUrl) {
    var base64 = dataUrl.split(",")[1];
    var binary = atob(base64);
    return Uint8Array.from(binary, function (c) {
      return c.charCodeAt(0);
    });
  }

  // Helper: detect image type from MIME
  function imageTypeFromMime(mime) {
    if (mime === "image/png") return "png";
    if (mime === "image/jpeg" || mime === "image/jpg") return "jpeg";
    if (mime === "image/gif") return "gif";
    if (mime === "image/bmp") return "bmp";
    return "png";
  }

  function addParagraph(content) {
    children.push(
      new docx.Paragraph({ children: content, spacing: { after: 200 } }),
    );
  }

  function addImage(dataUrl, width, height) {
    var mime = (dataUrl.split(",")[0].split(":")[1] || "").split(";")[0];
    var type = imageTypeFromMime(mime);
    var imgData = dataURLToUint8Array(dataUrl);
    addParagraph([
      new docx.ImageRun({
        data: imgData,
        type: type,
        transformation: { width: width, height: height },
      }),
    ]);
  }

  function addHeading(text, level) {
    children.push(
      new docx.Paragraph({
        children: [
          new docx.TextRun({
            text: text,
            bold: true,
            size: level === 1 ? 32 : 24,
            font: "Calibri",
          }),
        ],
        spacing: { after: 200 },
      }),
    );
  }

  function addBody(text) {
    children.push(
      new docx.Paragraph({
        children: [new docx.TextRun({ text: text, size: 20, font: "Calibri" })],
        spacing: { after: 100 },
      }),
    );
  }

  function addLabelValue(label, value) {
    if (!value) return;
    children.push(
      new docx.Paragraph({
        children: [
          new docx.TextRun({
            text: label + ": ",
            bold: true,
            size: 20,
            font: "Calibri",
          }),
          new docx.TextRun({ text: String(value), size: 20, font: "Calibri" }),
        ],
        spacing: { after: 60 },
      }),
    );
  }

  // Title
  addHeading("Digital Passport", 1);
  addBody(
    "Generated by RedoSan Authenticity — " +
      data.generatedAt.replace("T", " ").substring(0, 19),
  );

  // 1. User Info
  if (data.user.name) {
    addHeading("Owner", 2);
    addLabelValue("Name", data.user.name);
    addLabelValue("Email", data.user.email);
    addLabelValue("Phone", data.user.phone);
    addLabelValue("Website", data.user.website);
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 2. File Info
  addHeading("File Information", 2);
  addLabelValue("Name", data.file.name);
  addLabelValue("Size", fmtSize(data.file.size));
  if (data.file.width)
    addLabelValue(
      "Dimensions",
      data.file.width + " x " + data.file.height + " px",
    );
  if (data.file.hash) addLabelValue("SHA-256", data.file.hash);
  children.push(new docx.Paragraph({ spacing: { after: 200 } }));

  // Embed original image
  if (data.file.dataUrl) {
    var imgW = data.file.width || 400;
    var imgH = data.file.height || 400;
    var maxW = 400,
      maxH = 300;
    var scale = Math.min(maxW / imgW, maxH / imgH, 1);
    var dispW = Math.round(imgW * scale);
    var dispH = Math.round(imgH * scale);
    addImage(data.file.dataUrl, dispW, dispH);
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 4. Watermark
  if (data.watermark) {
    addHeading("Watermark", 2);
    addLabelValue("Result", data.watermarkAlgo || "Completed");
    if (data.watermarkResult) {
      addBody(data.watermarkResult);
    }
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 5. Pixel Injection
  if (data.pixelInjection) {
    addHeading("Pixel Injection", 2);
    addLabelValue("Result", "Completed");
    if (data.piResultHtml) {
      addBody(data.piResultHtml);
    }
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 5b. Document Watermark
  if (data.documentWatermark) {
    addHeading("Document Watermark", 2);
    addLabelValue("File", data.documentWatermarkFileName || "Completed");
    if (data.documentWatermarkResult) {
      addBody(data.documentWatermarkResult);
    }
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 6. Timestamp
  if (data.timestamp) {
    addHeading("Timestamp", 2);
    if (data.tsResult) {
      addBody(data.tsResult);
    } else {
      addBody("Timestamp created successfully.");
    }
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 7. Fingerprint
  if (data.fingerprint && data.fpResult && data.fpResult.hashes) {
    addHeading("Fingerprint (Hashes)", 2);
    var families = [
      { label: "SHA-1", keys: ["SHA-1"] },
      { label: "SHA-2", keys: ["SHA-224", "SHA-256", "SHA-384", "SHA-512"] },
      {
        label: "SHA-3",
        keys: ["SHA-3_224", "SHA-3_256", "SHA-3_384", "SHA-3_512"],
      },
      { label: "MD", keys: ["MD2", "MD4", "MD5"] },
      { label: "BLAKE", keys: ["BLAKE2b", "BLAKE2s", "BLAKE3"] },
      { label: "Other", keys: ["RIPEMD-160", "Whirlpool"] },
    ];
    for (var fi = 0; fi < families.length; fi++) {
      var fam = families[fi];
      var has = false;
      for (var ki = 0; ki < fam.keys.length; ki++) {
        if (data.fpResult.hashes[fam.keys[ki]]) {
          has = true;
          break;
        }
      }
      if (!has) continue;
      addHeading(fam.label, 2);
      for (ki = 0; ki < fam.keys.length; ki++) {
        var v = data.fpResult.hashes[fam.keys[ki]];
        if (v) addLabelValue(fam.keys[ki], v);
      }
      await new Promise(function (r) {
        setTimeout(r, 0);
      });
    }
    // Perceptual hashes
    if (data.fpResult.perceptual_hashes) {
      addHeading("Perceptual Hashes", 2);
      for (var pk in data.fpResult.perceptual_hashes) {
        addLabelValue(pk, data.fpResult.perceptual_hashes[pk]);
      }
    }
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 8. DID Signature
  if (data.didSig && data.didSig.did) {
    addHeading("Decentralized Identity (DID)", 2);
    addLabelValue("DID", data.didSig.did);
    addLabelValue("Algorithm", data.didSig.algorithm || "Ed25519");
    addLabelValue(
      "Signed",
      (data.didSig.timestamp || "").replace("T", " ").substring(0, 19),
    );
    addLabelValue(
      "Signature",
      (data.didSig.signature || "").substring(0, 64) + "...",
    );
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  } else if (data.didIdentity) {
    addHeading("DID Identity", 2);
    addLabelValue("DID", data.didIdentity);
    children.push(new docx.Paragraph({ spacing: { after: 200 } }));
  }

  // 9. Certificate Transparency
  if (data.ct && data.ct.submitted && data.ct.hash) {
    addHeading("Certificate Transparency", 2);
    addLabelValue("SHA-256", data.ct.hash);
    if (data.ct.pending) {
      // hash only, no status text
    } else {
      addLabelValue(
        "Logged",
        (data.ct.timestamp || "").replace("T", " ").substring(0, 19),
      );
      var shortAgg =
        (data.ct.aggregator || "").replace("https://", "").split("/")[0] ||
        "OTS calendar";
      addLabelValue("Transparency log", shortAgg);
    }
    addBody("Verifiable at: https://opentimestamps.org");
    children.push(new docx.Paragraph({ spacing: { after: 100 } }));
  } else if (data.ct) {
    addHeading("Certificate Transparency", 2);
    addBody(
      "Status: " +
        (data.ct.submitted
          ? "Submitted"
          : "Unavailable — " + (data.ct.error || "offline")),
    );
    children.push(new docx.Paragraph({ spacing: { after: 100 } }));
  }

  // 10. QR Verification Code
  var qrVerData = buildQRVerificationJSON(data);
  var docHash = await getDocHash(qrVerData);
  var qrContent = JSON.stringify({
    data: JSON.parse(qrVerData),
    hash: docHash,
  });
  var qrDataUrl = generateQRDataURL(qrContent, 400);
  children.push(new docx.Paragraph({ spacing: { after: 100 } }));
  addHeading("Verification QR Code", 2);
  addBody(
    "Scan this QR code to verify the document contents. The QR encodes all verification data (hashes, file info, owner). Any mismatch indicates tampering.",
  );
  addImage(qrDataUrl, 150, 150);
  children.push(new docx.Paragraph({ spacing: { after: 100 } }));

  await new Promise(function (r) {
    setTimeout(r, 0);
  });
  var docObj = new docx.Document({ sections: [{ children: children }] });
  var blob = await docx.Packer.toBlob(docObj);
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url;
  a.download = "RedoSan_Digital_Passport.docx";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(function () {
    URL.revokeObjectURL(url);
  }, 1000);
  return blob;
}
