converter:
  - any: ["Converter/**/*"]
c2pa:
  - any: ["C2PA/**/*"]
certificate:
  - any: ["Certificate/**/*"]
fingerprint:
  - any: ["Fingerprint/**/*"]
metadata:
  - any: ["Metadata/**/*"]
timestamp:
  - any: ["Timestamp/**/*"]
watermark:
  - any: ["Watermark/**/*"]
cli:
  - any: ["cli/**/*"]
i18n:
  - any: ["Style/lang/**/*"]
css:
  - any: ["Style/*.css"]
ci:
  - any: [".github/workflows/**/*"]
