(function () {
  if (
    typeof window != "undefined" &&
    window.location &&
    window.location.protocol !== "file:" &&
    !/^https?:\/\/(.*\.)?(redo-san\.github\.io|localhost|127\.0\.0\.1)(:\d+)?(\/|$)/.test(
      window.location.href,
    )
  )
    throw new Error(
      "RedoSan Authenticity: This script is protected by GPL license.",
    );
})();
// ── Professional Report Generator ──

var _docwEscXml = (function () {
  var map = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" };
  return function (s) {
    return String(s).replace(/[&<>"]/g, function (m) {
      return map[m];
    });
  };
})();

async function _docwHash(text) {
  var enc = new TextEncoder().encode(text);
  var hashBuf = await crypto.subtle.digest("SHA-256", enc);
  var hashArr = new Uint8Array(hashBuf);
  var hex = "";
  for (var i = 0; i < hashArr.length; i++) {
    hex += ("0" + hashArr[i].toString(16)).slice(-2);
  }
  return hex;
}

function _docwQrDataURL(text) {
  if (typeof QRious === "undefined") return null;
  var canvas = document.createElement("canvas");
  new QRious({
    element: canvas,
    value: text,
    size: 200,
    level: "H",
    padding: 4,
  });
  return canvas.toDataURL("image/png");
}

async function _docwBuildReportPdf(r, mode) {
  var isExtract = mode === "extract";
  var algo = isExtract ? r.algo || "" : r.algo || "";
  var ts = isExtract ? r.timestamp || "" : r.timestamp || "";
  var content = isExtract
    ? r.message || ""
    : _docwBuildCertificateText(r);
  var hash = isExtract
    ? await _docwHash(r.message || "")
    : (r.hash || "").replace("SHA-256:", "") || await _docwHash(r.watermarkedText || "");
  var qrContent = JSON.stringify({
    hash: hash,
    algo: algo,
    timestamp: ts,
    type: isExtract ? "extract" : "embed",
  });
  var qrData = _docwQrDataURL(qrContent);

  var doc = new jspdf.jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });
  var pw = doc.internal.pageSize.getWidth();
  var ph = doc.internal.pageSize.getHeight();
  var lm = 20, rm = 20, y = 20;
  var maxW = pw - lm - rm;

  // ── Title ──
  doc.setFontSize(16);
  doc.setTextColor(30, 30, 50);
  doc.text(
    isExtract ? "Extracted Watermark Report" : "Document Watermark Certificate",
    pw / 2, y, { align: "center" }
  );
  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 140);
  doc.text("Digital Authenticity Certificate — Generated by RedoSan Authenticity", pw / 2, y, { align: "center" });
  y += 12;

  // ── Separator ──
  doc.setDrawColor(180, 180, 195);
  doc.line(lm, y, pw - rm, y);
  y += 6;

  // ── Metadata ──
  var metaPairs = [
    ["Algorithm", algo],
    ["Timestamp", ts ? new Date(ts).toLocaleString() : ""],
    ["Content Length", content.length + " characters"],
    ["SHA-256", hash],
  ];
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 80);
  for (var mi = 0; mi < metaPairs.length; mi++) {
    doc.text(metaPairs[mi][0] + ":  " + metaPairs[mi][1], lm, y);
    y += 5;
  }
  y += 4;

  // ── Separator ──
  doc.setDrawColor(180, 180, 195);
  doc.line(lm, y, pw - rm, y);
  y += 6;

  // ── Section title ──
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 50);
  doc.text(isExtract ? "Extracted Message" : "Watermark Certificate", lm, y);
  y += 7;

  // ── Content (plain text, auto-wrapped, page breaks) ──
  doc.setFontSize(8);
  doc.setTextColor(60, 60, 80);
  var textLines = doc.splitTextToSize(content, maxW);
  for (var li = 0; li < textLines.length; li++) {
    if (y + 4 > ph - 15) {
      doc.addPage();
      y = 15;
    }
    doc.text(textLines[li], lm, y);
    y += 4;
  }
  y += 6;

  // ── QR Code ──
  if (qrData) {
    if (y + 65 > ph - 15) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 50);
    doc.text("Verification QR Code", pw / 2, y, { align: "center" });
    y += 4;
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 140);
    doc.text("Scan to verify document integrity", pw / 2, y, { align: "center" });
    y += 3;
    try {
      doc.addImage(qrData, "PNG", pw / 2 - 30, y, 60, 60);
    } catch (e) {}
    y += 64;
  }

  // ── Footer ──
  doc.setFontSize(6);
  doc.setTextColor(160, 160, 175);
  doc.text(
    "Generated by RedoSan Authenticity (redo-san.github.io) — " + new Date().toISOString().split("T")[0],
    pw / 2, ph - 8, { align: "center" }
  );
  if (hash)
    doc.text("SHA-256: " + hash, pw / 2, ph - 4, { align: "center" });

  return doc.output("blob");
}

async function _docwBuildReportDocx(r, mode) {
  var isExtract = mode === "extract";
  var algo = isExtract ? r.algo || "" : r.algo || "";
  var ts = isExtract ? r.timestamp || "" : r.timestamp || "";
  var content = isExtract
    ? r.message || ""
    : _docwBuildCertificateText(r);
  var hash = isExtract
    ? await _docwHash(r.message || "")
    : (r.hash || "").replace("SHA-256:", "") || await _docwHash(r.watermarkedText || "");
  var dateStr = ts
    ? new Date(ts).toLocaleString()
    : new Date().toLocaleString();

  var xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
  xml +=
    '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">';
  xml += "<w:body>";

  // Title
  xml +=
    '<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="200"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="28"/><w:color w:val="2D2D3A"/></w:rPr><w:t>' +
    _docwEscXml(
      isExtract ? "EXTRACTED WATERMARK REPORT" : "DOCUMENT WATERMARK REPORT",
    ) +
    "</w:t></w:r></w:p>";

  // Subtitle
  xml +=
    '<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="400"/></w:pPr><w:r><w:rPr><w:sz w:val="18"/><w:color w:val="6C5CE7"/></w:rPr><w:t>Digital Authenticity Certificate — RedoSan Authenticity</w:t></w:r></w:p>';

  // Metadata table
  xml +=
    '<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="pct"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="D0D0E0"/><w:bottom w:val="single" w:sz="4" w:color="D0D0E0"/><w:insideH w:val="single" w:sz="4" w:color="D0D0E0"/></w:tblBorders></w:tblPr>';
  var metaRows = [
    ["Algorithm", algo],
    ["Date/Time", dateStr],
    ["Content Length", content.length + " characters"],
    ["SHA-256", hash],
  ];
  for (var mri = 0; mri < metaRows.length; mri++) {
    xml +=
      '<w:tr><w:tc><w:tcW w:w="2000" w:type="dxa"/><w:p><w:r><w:rPr><w:b/><w:sz w:val="18"/></w:rPr><w:t>' +
      _docwEscXml(metaRows[mri][0]) +
      "</w:t></w:r></w:p></w:tc>";
    xml +=
      '<w:tc><w:tcW w:w="5000" w:type="dxa"/><w:p><w:r><w:rPr><w:sz w:val="18"/></w:rPr><w:t>' +
      _docwEscXml(metaRows[mri][1]) +
      "</w:t></w:r></w:p></w:tc></w:tr>";
  }
  xml += "</w:tbl><w:p><w:r><w:br/></w:r></w:p>";

  // Content section
  xml +=
    '<w:p><w:pPr><w:spacing w:after="200"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="22"/></w:rPr><w:t>' +
    _docwEscXml(isExtract ? "Extracted Message" : "Watermarked Content") +
    "</w:t></w:r></w:p>";
  xml +=
    '<w:p><w:r><w:rPr><w:sz w:val="18"/><w:color w:val="404050"/></w:rPr><w:t>' +
    _docwEscXml(content) +
    "</w:t></w:r></w:p>";

  xml += "</w:body></w:document>";

  var zip = new JSZip();
  zip.file("word/document.xml", xml);
  zip.file(
    "[Content_Types].xml",
    '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>',
  );
  zip.file(
    "_rels/.rels",
    '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
  );
  zip.file(
    "word/_rels/document.xml.rels",
    '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
  );
  return await zip.generateAsync({ type: "blob" });
}

function _docwBuildReportHtml(r, mode) {
  var isExtract = mode === "extract";
  var algo = isExtract ? r.algo || "" : r.algo || "";
  var ts = isExtract ? r.timestamp || "" : r.timestamp || "";
  var content = isExtract ? r.message || "" : _docwBuildCertificateText(r);
  var hashVal = isExtract ? "" : (r.hash || "").replace("SHA-256:", "");
  var dateStr = ts
    ? new Date(ts).toLocaleString()
    : new Date().toLocaleString();

  return (
    '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">' +
    "<title>" +
    (isExtract ? "Extracted Watermark Report" : "Document Watermark Report") +
    "</title>" +
    "<style>" +
    'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:800px;margin:30px auto;padding:0 24px;color:#2D2D3A;background:#F8F8FC}' +
    ".header{background:#6C5CE7;color:#fff;padding:16px 24px;border-radius:12px 12px 0 0;margin:-30px -24px 0;text-align:center}" +
    ".header h1{font-size:20px;margin:0}" +
    ".header p{font-size:12px;margin:4px 0 0;opacity:0.85}" +
    ".section{margin:24px 0}" +
    ".section h2{font-size:15px;border-bottom:2px solid #6C5CE7;padding-bottom:6px;margin:0 0 12px}" +
    "table{width:100%;border-collapse:collapse;font-size:13px}" +
    "td{padding:7px 10px;border:1px solid #E0E0EE}" +
    "td:first-child{font-weight:600;width:160px;background:#F0F0F8}" +
    '.content-box{background:#FAFAFC;border:1px solid #D0D0E0;border-radius:8px;padding:14px;font-family:"Courier New",monospace;font-size:12px;white-space:pre-wrap;word-break:break-all;line-height:1.6;max-height:400px;overflow:auto}' +
    ".qr-section{text-align:center;margin:24px 0}" +
    ".qr-section img{width:140px;height:140px}" +
    ".footer{margin-top:30px;padding-top:12px;border-top:1px solid #E0E0EE;font-size:11px;color:#888;text-align:center}" +
    '.fingerprint{font-family:"Courier New",monospace;font-size:11px;background:#F0F0F8;padding:6px 10px;border-radius:4px;word-break:break-all}' +
    "</style></head><body>" +
    '<div class="header"><h1>' +
    (isExtract ? "Extracted Watermark Report" : "Document Watermark Report") +
    "</h1><p>Digital Authenticity Certificate — Generated by RedoSan Authenticity</p></div>" +
    '<div class="section"><h2>Metadata</h2><table>' +
    "<tr><td>Algorithm</td><td>" +
    _docwEscXml(algo) +
    "</td></tr>" +
    "<tr><td>Date/Time</td><td>" +
    _docwEscXml(dateStr) +
    "</td></tr>" +
    "<tr><td>Content Length</td><td>" +
    content.length +
    " characters</td></tr>" +
    '<tr><td>SHA-256</td><td class="fingerprint" id="docw-hash"></td></tr>' +
    "</table></div>" +
    '<div class="section"><h2>' +
    (isExtract ? "Extracted Message" : "Watermark Certificate") +
    "</h2>" +
    '<div class="content-box">' +
    _docwEscXml(content) +
    "</div></div>" +
    '<div class="qr-section" id="docw-qr-section"></div>' +
    '<div class="footer">Generated by <a href="https://redo-san.github.io/RedoSan-Authenticity/">RedoSan Authenticity</a> — 100% Client-Side &bull; ' +
    new Date().toISOString().split("T")[0] +
    "</div>" +
    "<script>" +
    (isExtract
      ? 'crypto.subtle.digest("SHA-256",new TextEncoder().encode(' +
        JSON.stringify(content) +
        ')).then(function(b){var h="";new Uint8Array(b).forEach(function(v){h+=("0"+v.toString(16)).slice(-2)});document.getElementById("docw-hash").textContent=h;' +
        'new QRious({element:document.createElement("canvas"),value:JSON.stringify({hash:h,algo:' +
        JSON.stringify(algo) +
        ",timestamp:" +
        JSON.stringify(ts) +
        '}),size:140,level:"H",padding:4});'
      : 'document.getElementById("docw-hash").textContent=' +
        JSON.stringify(hashVal) +
        ";"
    ) +
    'var qr=document.createElement("canvas");' +
    "new QRious({element:qr,value:JSON.stringify({hash:" +
    (isExtract ? "h" : JSON.stringify(hashVal)) +
    ",algo:" +
    JSON.stringify(algo) +
    ",timestamp:" +
    JSON.stringify(ts) +
    '}),size:140,level:"H",padding:4});' +
    'var img=document.createElement("img");img.src=qr.toDataURL();img.alt="Verification QR Code";' +
    'document.getElementById("docw-qr-section").appendChild(img)' +
    (isExtract ? "})" : "") +
    "</script>" +
    "</body></html>"
  );
}
