import js from "@eslint/js";
import globals from "globals";
import sonarjs from "eslint-plugin-sonarjs";
import security from "eslint-plugin-security";
import jsdoc from "eslint-plugin-jsdoc";
import i18n from "eslint-plugin-i18n";
import unicorn from "eslint-plugin-unicorn";
import importX from "eslint-plugin-import-x";
import promise from "eslint-plugin-promise";
import compat from "eslint-plugin-compat";

export default [
  js.configs.recommended,
  unicorn.configs.recommended,
  promise.configs["flat/recommended"],
  {
    plugins: {
      sonarjs,
      security,
      jsdoc,
      i18n,
      "import-x": importX,
      compat,
    },
    rules: {
      ...sonarjs.configs.recommended.rules,
      ...security.configs.recommended.rules,
      ...jsdoc.configs["flat/recommended"].rules,
      ...i18n.configs.recommended.rules,
      ...importX.configs.recommended.rules,
      ...compat.configs.recommended.rules,
      "no-undef": "off",
      "no-unused-vars": "warn",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/no-null": "off",
      "unicorn/filename-case": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/no-array-reduce": "off",
      "unicorn/no-await-expression-member": "off",
      "unicorn/no-useless-undefined": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/no-static-only-class": "off",
      "unicorn/prefer-string-slice": "off",
      "unicorn/prefer-module": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/no-for-loop": "off",
      "unicorn/prefer-query-selector": "off",
      "unicorn/prefer-add-event-listener": "off",
      "unicorn/prefer-blob-reading-methods": "off",
      "unicorn/no-nested-ternary": "off",
      "unicorn/no-abusive-eslint-disable": "off",
      "unicorn/no-empty-file": "off",
      "sonarjs/block-scoped-var": "off",
      "sonarjs/no-nested-functions": "off",
      "sonarjs/no-nested-template-literals": "off",
      "promise/param-names": "off",
      "compat/compat": "off",
      "sonarjs/cognitive-complexity": ["warn", 30],
      "unicorn/prefer-code-point": "off",
      "unicorn/text-encoding-identifier-case": "off",
      "unicorn/no-array-push-push": "off",
      "unicorn/prefer-number-properties": "off",
      "unicorn/prefer-spread": "off",
      "unicorn/no-new-array": "off",
      "unicorn/prefer-default-parameters": "off",
      "unicorn/prefer-math-trunc": "off",
      "unicorn/prefer-structured-clone": "off",
      "unicorn/prefer-top-level-await": "off",
      "unicorn/prefer-dom-node-text-content": "off",
      "unicorn/explicit-length-check": "off",
      "unicorn/no-useless-spread": "off",
      "unicorn/number-literal-case": "off",
      "unicorn/consistent-existence-index-check": "off",
      "unicorn/consistent-boolean-name": "off",
      "unicorn/no-break-in-nested-loop": "off",
      "unicorn/no-computed-property-existence-check": "off",
      "unicorn/no-for-each": "off",
      "unicorn/prefer-includes-over-repeated-comparisons": "off",
      "unicorn/prefer-unicode-code-point-escapes": "off",
      "unicorn/prefer-string-replace-all": "off",
      "unicorn/prefer-await": "off",
      "unicorn/no-top-level-assignment-in-function": "off",
      "unicorn/prefer-early-return": "off",
      "unicorn/no-this-outside-of-class": "off",
      "unicorn/no-invalid-argument-count": "off",
      "unicorn/no-useless-else": "off",
      "unicorn/no-unnecessary-nested-ternary": "off",
      "unicorn/prefer-number-coercion": "off",
      "unicorn/no-useless-recursion": "off",
      "unicorn/no-duplicate-set-values": "off",
      "unicorn/prefer-global-this": "off",
      "unicorn/no-unnecessary-global-this": "off",
      "unicorn/logical-assignment-operators": "off",
      "unicorn/no-negated-array-predicate": "off",
      "unicorn/no-unreadable-array-destructuring": "off",
      "unicorn/no-incorrect-template-string-interpolation": "off",
      "unicorn/no-unsafe-string-replacement": "off",
      "unicorn/prefer-object-iterable-methods": "off",
      "sonarjs/no-unused-vars": "off",
      "sonarjs/no-dead-store": "off",
      "sonarjs/void-use": "off",
      "sonarjs/single-char-in-character-classes": "off",
      "sonarjs/concise-regex": "off",
      "sonarjs/prefer-single-boolean-return": "off",
      "sonarjs/no-unenclosed-multiline-block": "off",
      "sonarjs/constructor-for-side-effects": "off",
      "sonarjs/no-unused-collection": "off",
      "sonarjs/no-gratuitous-expressions": "off",
      "preserve-caught-error": "off",
      "sonarjs/no-useless-catch": "off",
      "sonarjs/no-extra-arguments": "off",
      "sonarjs/function-inside-loop": "off",
      "sonarjs/pseudo-random": "off",
      "no-useless-assignment": "off",
      "no-useless-escape": "off",
      "no-useless-catch": "off",
      "import-x/no-unresolved": "warn",
      "import-x/no-named-as-default": "off",
      "import-x/no-named-as-default-member": "off",
      "import-x/namespace": "off",
      "no-empty": "off",
      "no-duplicate-case": "off",
      "sonarjs/slow-regex": "off",
      "sonarjs/no-nested-conditional": "off",
      "sonarjs/code-eval": "off",
      "sonarjs/no-all-duplicated-branches": "off",
      "sonarjs/no-identical-functions": "off",
      "sonarjs/no-identical-conditions": "off",
      "sonarjs/no-hardcoded-passwords": "off",
      "sonarjs/os-command": "off",
      "sonarjs/no-duplicated-branches": "off",
      "sonarjs/no-os-command-from-path": "off",
      "sonarjs/hardcoded-secret-signatures": "off",
      "promise/always-return": "off",
      "promise/catch-or-return": "off",
      "unicorn/numeric-separators-style": "off",
      "unicorn/catch-error-name": "off",
      "unicorn/switch-case-braces": "off",
      "sonarjs/no-ignored-exceptions": "off",
      "unicorn/prefer-optional-catch-binding": "off",
      "no-redeclare": "off",
      "unicorn/prefer-node-protocol": "off",
      "unicorn/prefer-dom-node-append": "off",
      "unicorn/prefer-single-call": "off",
      "sonarjs/super-linear-regex": "off",
      "unicorn/prefer-includes": "off",
      "unicorn/no-negated-condition": "off",
      "unicorn/prefer-switch": "off",
      "unicorn/no-zero-fractions": "off",
      "unicorn/prefer-split-limit": "off",
      "unicorn/prefer-ternary": "off",
      "unicorn/no-typeof-undefined": "off",
      "unicorn/no-hex-escape": "off",
      "unicorn/dom-node-dataset": "off",
      "unicorn/prefer-dom-node-remove": "off",
      "unicorn/no-immediate-mutation": "off",
      "unicorn/prefer-string-raw": "off",
      "unicorn/escape-case": "off",
      "unicorn/prefer-at": "off",
      "unicorn/no-array-sort": "off",
      "sonarjs/no-domain-deserialize": "off",
      "sonarjs/reduce-with-no-initializer": "off",
      "sonarjs/no-collapsible-if": "off",
      "sonarjs/prefer-while": "off",
      "unicorn/import-index": "off",
      "unicorn/no-useless-fallback-in-spread": "off",
      "unicorn/no-unnecessary-fetch-callback-function": "off",
      "unicorn/prefer-blob-reading-methods": "off",
      "unicorn/prefer-dom-node-dataset": "off",
      "unicorn/no-unnecessary-check": "off",
      "unicorn/prefer-import-from-array": "off",
      "unicorn/prefer-regexp-test": "off",
      "unicorn/prefer-math": "off",
      "unicorn/consistent-return": "off",
      "unicorn/throw-new-error": "off",
      "unicorn/relative-url-style": "off",
      "unicorn/error-message": "off",
      "sonarjs/use-numeric-separators": "off",
      "unicorn/prefer-modern-math-apis": "off",
      "no-dupe-keys": "off",
      "unicorn/prefer-type-error": "off",
      "unicorn/prefer-bigint-literals": "off",
      "sonarjs/no-implicit-global": "off",
      "unicorn/prefer-https": "off",
      "unicorn/new-for-builtins": "off",
      "unicorn/require-css-escape": "off",
      "unicorn/prefer-set-has": "off",
      "unicorn/prefer-classlist-toggle": "off",
      "unicorn/no-lonely-if": "off",
      "no-dupe-else-if": "off",
      "unicorn/prefer-negative-index": "off",
      "security/detect-unsafe-regex": "warn",
      "security/detect-object-injection": "warn",
      "jsdoc/require-jsdoc": "warn",
      "jsdoc/require-param": "off",
      "jsdoc/require-returns": "off",
      "jsdoc/no-undefined-types": "off",
      "jsdoc/require-param-type": "off",
      "jsdoc/check-param-names": "off",
      "jsdoc/check-tag-names": "off",
      "i18n/no-missing-placeholders": "off",
      "import-x/default": "off",
      "import-x/no-duplicates": "off",
      "no-var": "off",
      "prefer-const": "off",
      "no-empty-pattern": "off",
      "no-prototype-builtins": "off",
      "no-control-regex": "off",
      "no-unexpected-multiline": "off",
      "no-func-assign": "off",
      "no-sparse-arrays": "off",
      "no-unsafe-optional-chaining": "off",
    },
    settings: {
      "import-x/resolver": {
        node: true,
      },
    },
  },
  {
    files: ["cli/**", "scripts/**"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.node,
        ...globals.es2022,
      },
    },
  },
  {
    files: ["Style/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
    },
  },
  {
    files: ["sw.js"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.serviceworker,
        ...globals.es2022,
      },
    },
  },
  {
    files: [
      "Fingerprint/hashing.js",
      "Fingerprint/hashing_perceptual.js",
      "Audio_Watermark/audio_watermark_core.js",
      "Decentralized_Identity_DID/did.js",
    ],
    rules: {
      "no-redeclare": "off",
    },
  },
  {
    ignores: [
      "node_modules/",
      "vendor/",
      "**/*.min.js",
      "C2PA/",
      "Pixel_Injection/watermark_core_advanced.js",
      "Style/lang/i18n-data.js",
      "cli/tests/",
      "cli/lib/",
    ],
  },
];
