var fs = require("fs");
var c = fs.readFileSync(
  "cli/tests/e2e/mpa/mpa_voice_biometric_test.js",
  "utf8",
);
var old =
  'async function dumpRegistry(page, label) {\n  return page\n    .evaluate(async function () {\n      return new Promise(function (resolve) {\n        var req = indexedDB.open("VoiceRegistryDB", 2);\n        req.onsuccess = function () {\n          var db = req.result;\n          if (!db.objectStoreNames.contains("registrations")) {\n            resolve({ registrations: [], templates: [] });\n            return;\n          }\n          var tx = db.transaction(["registrations", "templates"], "readonly");\n          var regStore = tx.objectStore("registrations");\n          var tmplStore = tx.objectStore("templates");\n          var regReq = regStore.getAll();\n          var tmplReq = tmplStore.getAll();\n          regReq.onsuccess = function () {\n            tmplReq.onsuccess = function () {\n              resolve({\n                registrations: regReq.result,\n                templates: tmplReq.result,\n              });\n            };\n          };\n        };\n        req.onerror = function () {\n          resolve({ registrations: [], templates: [] });\n        };\n      });\n    })\n    .catch(function () {\n      return { registrations: [], templates: [] };\n    });';
var nw =
  'async function dumpRegistry(page, label) {\n  return page.evaluate(async function () {\n    return new Promise(function (resolve) {\n      var req = indexedDB.open("VoiceRegistryDB", 2);\n      req.onsuccess = function () {\n        var db = req.result;\n        if (!db.objectStoreNames.contains("templates")) {\n          resolve({ templates: [], consent: [], auth: [], meta: [] });\n          return;\n        }\n        var tx = db.transaction(["templates", "consent", "auth", "meta"], "readonly");\n        var tmplStore = tx.objectStore("templates");\n        var consentStore = tx.objectStore("consent");\n        var authStore = tx.objectStore("auth");\n        var metaStore = tx.objectStore("meta");\n        var tmplReq = tmplStore.getAll();\n        var consentReq = consentStore.getAll();\n        var authReq = authStore.getAll();\n        var metaReq = metaStore.getAll();\n        tmplReq.onsuccess = function () {\n          consentReq.onsuccess = function () {\n            authReq.onsuccess = function () {\n              metaReq.onsuccess = function () {\n                resolve({ \n                  templates: tmplReq.result, \n                  consent: consentReq.result, \n                  auth: authReq.result, \n                  meta: metaReq.result \n                });\n              };\n            };\n          };\n        };\n      };\n      req.onerror = function () { resolve({ templates: [], consent: [], auth: [], meta: [] }); };\n    });\n  }).catch(function () { return { templates: [], consent: [], auth: [], meta: [] }; });';
c = c.split(old).join(nw);
fs.writeFileSync("cli/tests/e2e/mpa/mpa_voice_biometric_test.js", c);
console.log("done");
