#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# RedoSan Authenticity — npm Phase B: account, first release, trusted publisher.
#
# Why this wizard exists (plan §6.5): npm refuses to configure a trusted
# publisher for a package that does not exist yet (docs.npmjs.com/cli/v12/
# commands/npm-trust — "Package must exist"), so the OIDC/CI path cannot create
# the package. Staged publishing can: "Staged publishing will allow you to
# create a new package if it does not exist" — it drops a public 0.0.0-stage
# placeholder on the registry, after which `npm trust` becomes legal. So the
# order is: login → 2FA → stage (package appears) → trust (stage-only) →
# approve (v1.0.0 live). No `npm publish` anywhere; dual-use stays satisfied.
#
# Nothing is written to $ENV_FILE and no GitHub secret is set: OIDC trusted
# publishing stores no npm token in the repo, and the only id this flow
# produces (stage-id) is recovered on demand with `npm stage list`.

PKG_NAME="redosan-authenticity-cli"
PKG_VERSION="1.0.0"
GH_OWNER="Redo-San"
GH_REPO="RedoSan-Authenticity"
TRUST_WORKFLOW="publish-npm.yml"

# `npm stage` and `npm trust` both require npm >= 11.15.0; the CLI bundled on
# this machine is 10.x, and upgrading it in place is forbidden here (C5: npm <
# 11 strips `libc` markers on Windows). So every npm call goes through a pinned
# modern CLI via npx — no global install, no change to package-lock.json.
npm11() { npx -y npm@11.20.0 "$@"; }

# All npm commands below are the ones verified from `npm ... --help` and
# docs.npmjs.com at authoring time. Do not add npmjs.com application URLs: that
# host returns 403 to every automated request, so no deep link can be verified.
DOCS_ACCOUNT="https://docs.npmjs.com/creating-a-new-npm-user-account/"
DOCS_2FA="https://docs.npmjs.com/configuring-two-factor-authentication/"

TOTAL_STAGES=8
TOTAL_MINUTES=30

banner "RedoSan Authenticity — npm publish setup"

# ── Stage 1 — preflight ───────────────────────────────────────────────────
stage "Preflight" 2
say "Nothing leaves your machine here. We abort if any check fails, because a"
say "half-published package cannot be unpublished under npm's policy."
note "repo root: $(pwd)"

if [[ ! -f package.json ]]; then
  warn "no package.json here — run this from the repo (scripts/ lives one level down)."
  exit 1
fi

pkg_line=$(node -p "const p=require('./package.json');p.name+'@'+p.version+' ('+p.license+')'")
say "package: $pkg_line"

if [[ "$(node -p "require('./package.json').name")" != "$PKG_NAME" ]]; then
  warn "package.json name is not $PKG_NAME — refusing to continue."
  exit 1
fi
if [[ "$(node -p "require('./package.json').version")" != "$PKG_VERSION" ]]; then
  warn "package.json version is not $PKG_VERSION — refusing to continue."
  exit 1
fi
if [[ "$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')" != "main" ]]; then
  warn "not on main — switching is your call, but this flow expects main."
  exit 1
fi
if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
  warn "working tree is dirty. Commit or stash first so we publish exactly main:"
  git status --short
  exit 1
fi
note "branch main · clean tree"

# Name-availability probe. `npm view` exits 0 when the package exists; any
# other failure must be a real 404, not a network blip, before we call it free.
view_out=$(npm11 view "$PKG_NAME" version 2>&1) && {
  warn "$PKG_NAME already exists on the npm registry."
  exit 1
} || true
if ! printf '%s' "$view_out" | grep -qiE 'E404|not ?found|404'; then
  warn "could not confirm the name is free — not guessing:"
  printf '%s\n' "$view_out"
  exit 1
fi
say "name '$PKG_NAME' is free on the registry ✓"

# ── Stage 2 — npm 11.15+ ──────────────────────────────────────────────────
stage "npm CLI 11.15+ (via npx)" 2
say "Bundled npm here is $(npm -v). Both 'stage' and 'trust' need 11.15.0+,"
say "so we drive a pinned npm@11.20.0 through npx instead of upgrading yours."
if ! npm11 stage --help >/dev/null 2>&1; then
  warn "npm@11.20.0 has no 'stage' subcommand — cannot continue."
  exit 1
fi
if ! npm11 trust --help >/dev/null 2>&1; then
  warn "npm@11.20.0 has no 'trust' subcommand — cannot continue."
  exit 1
fi
note "npx -y npm@11.20.0 → $(npm11 -v 2>/dev/null | tail -n1) · stage ✓ trust ✓"

# ── Stage 3 — account + login ─────────────────────────────────────────────
stage "npm account + login" 4
say "npm login opens your browser and polls until you approve. The session is"
say "registry-side, so it works for both npm 10 and npm 11 below."
if ! confirm "Do you already have an npm account (user $GH_OWNER or similar)?"; then
  open_url "$DOCS_ACCOUNT"
  pause "Create the account in the browser, then press Enter."
fi
step "Running: npm login  (approve it in the browser when it opens)"
if ! npm11 login; then
  warn "npm login failed."
  note "If npx swallowed the browser flow, run plain 'npm login' in another"
  note "terminal and re-run this wizard — the session is the same either way."
  exit 1
fi
if ! who=$(npm11 whoami 2>/dev/null); then
  warn "npm whoami failed — not actually logged in."
  exit 1
fi
say "logged in as: $who ✓"

# ── Stage 4 — 2FA ─────────────────────────────────────────────────────────
stage "Enable two-factor authentication" 4
say "Account-level 2FA is a hard prerequisite of 'npm trust' — even if you have"
say "never enabled it, npm will refuse the trust command until you do."
step "Mode auth-and-writes: 2FA for login and for write actions."
step "Running: npm profile enable-2fa auth-and-writes"
if npm11 profile enable-2fa auth-and-writes; then
  note "enable command completed."
else
  warn "command returned non-zero (already enabled, or it wants the browser flow)."
  open_url "$DOCS_2FA"
  pause "Enable 2FA in the browser using the docs link, then press Enter."
fi
if ! confirm "Is 2FA now enabled on the npm account?"; then
  warn "2FA is required. Re-run this wizard once it is enabled."
  exit 1
fi
note "2FA confirmed by you — stage 6 enforces it against npm itself."

# ── Stage 5 — stage v1.0.0 (creates the package) ──────────────────────────
stage "Stage $PKG_VERSION" 5
say "This is the first command that writes to the registry. npm publishes a"
say "public placeholder version '0.0.0-stage' (its own mechanism for creating a"
say "package that does not exist yet) and holds $PKG_VERSION invisible until"
say "you approve it in stage 7."
note "No --provenance here: provenance requires a CI environment, so it only"
note "appears from v1.0.1 onward, produced by GitHub Actions."
if ! confirm "Stage $PKG_NAME@$PKG_VERSION now?"; then
  warn "stopped before touching the registry."
  exit 1
fi
if ! npm11 stage publish; then
  warn "staging failed."
  note "Most likely: 2FA is not enabled, or you lack publish access to the name."
  exit 1
fi
say "staged. Capturing the stage-id..."

raw=$(npm11 stage list --json 2>&1) || true
STAGE_ID=$(printf '%s' "$raw" | node -e "
  let s = '';
  process.stdin.on('data', d => (s += d)).on('end', () => {
    try {
      const j = JSON.parse(s);
      const arr = Array.isArray(j) ? j
        : (j.staged || j.stages || j.items
           || Object.values(j).find(v => Array.isArray(v)) || []);
      const first = arr[0] || {};
      const id = first.id || first.stageId || first.stage_id || first.stageID;
      process.stdout.write(id ? String(id) : '');
    } catch (e) { process.stdout.write(''); }
  });
" 2>/dev/null) || STAGE_ID=""

if [[ -z "$STAGE_ID" ]]; then
  warn "could not parse the stage-id from 'npm stage list --json'."
  say "Raw output:"
  printf '%s\n' "$raw"
  ask STAGE_ID "Paste the stage-id for $PKG_VERSION:"
fi
if [[ -z "$STAGE_ID" ]]; then
  warn "no stage-id — re-run and paste it, or run: npx -y npm@11.20.0 stage list"
  exit 1
fi
say "stage-id: $STAGE_ID ✓"

# ── Stage 6 — trusted publisher (stage-only) ──────────────────────────────
stage "Trusted publisher — stage-only" 6
say "This is the security decision of the whole plan: grant ONLY"
say "'npm stage publish' and leave 'npm publish' disabled, so automation can"
say "never push a package live without your 2FA approval."
note "npm allows just ONE trust configuration per package."
step "Running: npm trust github $PKG_NAME --file $TRUST_WORKFLOW \\"
step "           --repo $GH_OWNER/$GH_REPO --allow-stage-publish -y"
if ! npm11 trust github "$PKG_NAME" \
      --file "$TRUST_WORKFLOW" \
      --repo "$GH_OWNER/$GH_REPO" \
      --allow-stage-publish -y; then
  warn "trust creation failed."
  note "Usual causes: 2FA not enabled (stage 4), the package not staged yet"
  note "(stage 5), or you lack write access to $PKG_NAME."
  exit 1
fi
list_out=$(npm11 trust list "$PKG_NAME" 2>&1) || true
printf '%s\n' "$list_out"
if printf '%s' "$list_out" | grep -q "$TRUST_WORKFLOW" \
   && printf '%s' "$list_out" | grep -q "$GH_REPO"; then
  say "trust confirmed: $GH_OWNER/$GH_REPO :: $TRUST_WORKFLOW (stage-only) ✓"
else
  warn "could not verify the trust output — check it yourself:"
  note "  npx -y npm@11.20.0 trust list $PKG_NAME"
fi
note "--allow-publish was NOT passed, so direct publish stays forbidden."

# ── Stage 7 — approve v1.0.0 ──────────────────────────────────────────────
stage "Approve $PKG_VERSION (2FA)" 5
say "Approving publishes the staged tarball. npm prompts for a one-time"
say "password — that prompt is the proof-of-presence npm's dual-use policy"
say "wants, and it is exactly what you will repeat for every later release."
step "Running: npm stage approve $STAGE_ID"
if ! npm11 stage approve "$STAGE_ID"; then
  warn "approval failed — $PKG_NAME is still staged and not live."
  note "Retry with: npx -y npm@11.20.0 stage approve $STAGE_ID"
  exit 1
fi
say "approved. Verifying against the registry..."

live_ver=$(npm11 view "$PKG_NAME" version 2>/dev/null) || live_ver=""
live_lic=$(npm11 view "$PKG_NAME" license 2>/dev/null) || live_lic=""
if [[ "$live_ver" != "$PKG_VERSION" ]]; then
  warn "registry reports version '$live_ver', expected '$PKG_VERSION'."
  exit 1
fi
if [[ "$live_lic" != "GPL-2.0-or-later" ]]; then
  warn "registry reports license '$live_lic', expected 'GPL-2.0-or-later'."
  exit 1
fi
say "$PKG_NAME@$live_ver · $live_lic ✓"
say "https://www.npmjs.com/package/$PKG_NAME"

# ── Stage 8 — handoff to Phase D ──────────────────────────────────────────
stage "Record the result, hand off to Phase D" 1
say "Phase B is done. Phase D proves the CI path on the next version:"
step "1. bump package.json version to 1.0.1 and commit on main"
step "2. git tag v1.0.1 && git push origin v1.0.1"
step "3. watch .github/workflows/publish-npm.yml → OIDC exchange → STAGED"
step "4. npx -y npm@11.20.0 stage list  →  stage approve <id>  (2FA)"
step "5. npm view $PKG_NAME  →  then Item 4g (libraries.io) auto-indexes"

PLAN_FILE=".Plans/OSS-EXECUTION-PLAN.md"
PLAN_MARK="<!-- wizard-npm-publish:phase-b -->"
if [[ -f "$PLAN_FILE" ]] && ! grep -qF "$PLAN_MARK" "$PLAN_FILE"; then
  {
    printf '\n%s\n' "$PLAN_MARK"
    printf 'Phase B completed %s via scripts/wizard-npm-publish.sh:\n' "$(date -u +%Y-%m-%dT%H:%MZ)"
    printf -- '- first release of %s v%s published locally with `npm stage publish` + `npm stage approve` (2FA)\n' "$PKG_NAME" "$PKG_VERSION"
    printf -- '- trusted publisher configured stage-only: %s/%s :: %s\n' "$GH_OWNER" "$GH_REPO" "$TRUST_WORKFLOW"
    printf -- '- local gate: `npm view %s` = v%s / GPL-2.0-or-later\n' "$PKG_NAME" "$PKG_VERSION"
    printf -- '- next: Phase D — bump 1.0.1, tag v1.0.1, CI stages, approve with 2FA\n'
    printf '%s\n' "$PLAN_MARK"
  } >> "$PLAN_FILE"
  say "appended Phase B result to $PLAN_FILE ✓"
else
  note "plan file not updated (missing, or already recorded)."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
