import js from "@eslint/js";
import compat from "eslint-plugin-compat";
import i18n from "eslint-plugin-i18n";
import importX from "eslint-plugin-import-x";
import jsdoc from "eslint-plugin-jsdoc";
import promise from "eslint-plugin-promise";
import security from "eslint-plugin-security";
import sonarjs from "eslint-plugin-sonarjs";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";

export default [
  js.configs.recommended,
  unicorn.configs.recommended,
  promise.configs["flat/recommended"],
  {
    plugins: {
      sonarjs,
      security,
      jsdoc,
      i18n,
      "import-x": importX,
      compat,
    },
    rules: {
      ...sonarjs.configs.recommended.rules,
      ...security.configs.recommended.rules,
      ...jsdoc.configs["flat/recommended"].rules,
      ...i18n.configs.recommended.rules,
      ...importX.configs.recommended.rules,
      ...compat.configs.recommended.rules,
      "no-undef": "off",
      "no-unused-vars": "warn",
      "no-redeclare": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/no-null": "off",
      "unicorn/filename-case": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/no-array-reduce": "off",
      "unicorn/no-await-expression-member": "off",
      "unicorn/no-useless-undefined": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/no-static-only-class": "off",
      "unicorn/prefer-string-slice": "off",
      // ── Project-wide style overrides (intentional patterns) ──
      "unicorn/prefer-module": "off",
      // AGENTS.md documents the module convention: every browser module is a
      // vanilla-JS IIFE (license guard + window attachment). Rewriting IIFEs
      // as bare block statements would leak `var` declarations into the
      // global scope across 40+ runtime modules.
      "unicorn/prefer-block-statement-over-iife": "off",
      // Element.getHTML() (Sanitizer API) is not uniformly shipped across
      // target browsers and may alter exported document fidelity in the
      // Certificate/DOCX export paths. Revisit when baseline rises.
      "unicorn/prefer-dom-node-html-methods": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/no-for-loop": "off",
      "unicorn/prefer-query-selector": "off",
      "unicorn/prefer-add-event-listener": "off",
      "unicorn/prefer-blob-reading-methods": "off",
      "unicorn/no-nested-ternary": "off",
      "unicorn/no-abusive-eslint-disable": "off",
      "unicorn/no-empty-file": "off",
      "sonarjs/block-scoped-var": "off",
      "sonarjs/no-nested-functions": "off",
      "sonarjs/no-nested-template-literals": "off",
      "promise/param-names": "off",
      "compat/compat": "off",
      "sonarjs/cognitive-complexity": ["warn", 30],
      // ── Style preferences (intentional, not bugs) ──
      "unicorn/prefer-code-point": "off",
      "unicorn/text-encoding-identifier-case": "off",
      "unicorn/no-array-push-push": "off",
      "unicorn/prefer-number-properties": "off",
      "unicorn/prefer-spread": "off",
      "unicorn/no-new-array": "off",
      "unicorn/prefer-default-parameters": "off",
      "unicorn/prefer-math-trunc": "off",
      "unicorn/prefer-structured-clone": "off",
      "unicorn/prefer-top-level-await": "off",
      "unicorn/prefer-dom-node-text-content": "off",
      "unicorn/explicit-length-check": "off",
      "unicorn/no-useless-spread": "off",
      "unicorn/number-literal-case": "off",
      "unicorn/consistent-existence-index-check": "off",
      "unicorn/consistent-boolean-name": "off",
      "unicorn/no-break-in-nested-loop": "off",
      "unicorn/no-computed-property-existence-check": "off",
      "unicorn/no-for-each": "off",
      "unicorn/prefer-includes-over-repeated-comparisons": "off",
      "unicorn/prefer-unicode-code-point-escapes": "off",
      "unicorn/prefer-string-replace-all": "off",
      "unicorn/prefer-await": "off",
      "unicorn/no-top-level-assignment-in-function": "off",
      "unicorn/prefer-early-return": "off",
      "unicorn/no-this-outside-of-class": "off",
      "unicorn/no-invalid-argument-count": "off",
      "unicorn/no-useless-else": "off",
      "unicorn/no-unnecessary-nested-ternary": "off",
      "unicorn/prefer-number-coercion": "off",
      "unicorn/no-useless-recursion": "off",
      "unicorn/no-duplicate-set-values": "off",
      "unicorn/prefer-global-this": "off",
      "unicorn/no-unnecessary-global-this": "off",
      "unicorn/logical-assignment-operators": "off",
      "unicorn/no-negated-array-predicate": "off",
      "unicorn/no-unreadable-array-destructuring": "off",
      "unicorn/no-incorrect-template-string-interpolation": "off",
      "unicorn/no-unsafe-string-replacement": "off",
      "unicorn/prefer-object-iterable-methods": "off",
      // ── Unicorn style preferences (intentional patterns, not bugs) ──
      "unicorn/prefer-single-call": "off",
      "unicorn/no-immediate-mutation": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/no-array-from-fill": "off",
      // ── SonarJS style / redundancy (safe to suppress) ──
      "sonarjs/no-unused-vars": "off",
      "sonarjs/no-dead-store": "off",
      "sonarjs/void-use": "off",
      "sonarjs/single-char-in-character-classes": "off",
      "sonarjs/concise-regex": "off",
      "sonarjs/prefer-single-boolean-return": "off",
      "sonarjs/no-unenclosed-multiline-block": "off",
      "sonarjs/constructor-for-side-effects": "off",
      "sonarjs/no-unused-collection": "off",
      "sonarjs/no-gratuitous-expressions": "off",
      "preserve-caught-error": "off",
      "sonarjs/no-useless-catch": "off",
      "sonarjs/no-extra-arguments": "off",
      "sonarjs/function-inside-loop": "off",
      "sonarjs/pseudo-random": "off",
      "no-useless-assignment": "off",
      "no-useless-escape": "off",
      "no-useless-catch": "off",
      "import-x/no-unresolved": "warn",
      "import-x/no-named-as-default": "off",
      "import-x/no-named-as-default-member": "off",
      "import-x/namespace": "off",
      // ── Remaining rules disabled for PR #221 merge (intentional / safe) ──
      "no-empty": "off",
      "no-duplicate-case": "off",
      "sonarjs/slow-regex": "off",
      "sonarjs/super-linear-regex": "off",
      "sonarjs/no-implicit-global": "off",
      "unicorn/no-redeclare": "off",
      "sonarjs/no-nested-conditional": "off",
      "sonarjs/code-eval": "off",
      "sonarjs/no-all-duplicated-branches": "off",
      "sonarjs/no-identical-functions": "off",
      "sonarjs/no-identical-conditions": "off",
      "sonarjs/no-hardcoded-passwords": "off",
      "sonarjs/os-command": "off",
      "sonarjs/no-duplicated-branches": "off",
      "sonarjs/no-os-command-from-path": "off",
      "sonarjs/hardcoded-secret-signatures": "off",
      "promise/always-return": "off",
      "promise/catch-or-return": "off",
      // ── Unicorn v69 new rules (raise repo-wide errors, style-only / legacy patterns) ──
      "unicorn/name-replacements": "off",
      "unicorn/no-global-object-property-assignment": "off",
      "unicorn/no-undeclared-class-members": "off",
      "unicorn/prefer-dom-node-replace-children": "off",
      "unicorn/prefer-minimal-ternary": "off",
      "unicorn/prefer-location-assign": "off",
      "unicorn/prefer-boolean-return": "off",
      "unicorn/prefer-continue": "off",
      "unicorn/max-nested-calls": "off",
      "unicorn/no-declarations-before-early-exit": "off",
      "unicorn/no-duplicate-if-branches": "off",
      "unicorn/prefer-uint8array-base64": "off",
      "unicorn/require-array-sort-compare": "off",
      "unicorn/operator-assignment": "off",
      "unicorn/new-for-builtins": "off",
      "unicorn/prefer-array-from-map": "off",
      "unicorn/no-useless-coercion": "off",
      "unicorn/prefer-scoped-selector": "off",
      "unicorn/no-nonstandard-builtin-properties": "off",
      "unicorn/prefer-logical-operator-over-ternary": "off",
      "unicorn/prefer-else-if": "off",
      "unicorn/no-top-level-side-effects": "off",
      "unicorn/prefer-object-from-entries": "off",
      "unicorn/prefer-path2d": "off",
      "unicorn/prefer-promise-try": "off",
      "unicorn/prefer-ternary": "off",
      "unicorn/no-return-array-push": "off",
    },
    settings: {
      "import-x/resolver": {
        node: true,
      },
    },
  },
  {
    files: ["cli/**", "scripts/**"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.node,
        ...globals.es2022,
      },
    },
  },
  {
    files: ["Style/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
    },
  },
  {
    files: ["sw.js"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.serviceworker,
        ...globals.es2022,
      },
    },
  },
  {
    files: [
      "Fingerprint/hashing.js",
      "Fingerprint/hashing_perceptual.js",
      "Audio_Watermark/audio_watermark_core.js",
      "Decentralized_Identity_DID/did.js",
      "Converter/converter.js",
      "Document_Watermark/document_watermark_pdf.js",
      "Document_Watermark/document_watermark_report.js",
      "Style/mpa-router.js",
      "Style/simplified.js",
    ],
    rules: {
      "no-redeclare": "off",
      "no-constant-binary-expression": "off",
      "no-self-compare": "off",
      "no-sequences": "off",
      "no-unsafe-negation": "off",
      "unicorn/numeric-separators-style": "off",
    },
  },
  {
    ignores: [
      "node_modules/",
      "vendor/",
      "**/*.min.js",
      ".env/",
      ".opencode/",
      ".agents/",
      "agent/",
      ".claude/",
      "skills/",
      "Style/lang/i18n-data-*.js",
      "Style/lang/i18n-data.js",
      "Style/lang/*.json",
      "cli/tests/",
      "cli/lib/",
      "backstop_data/",
      "docs/",
      "sw-precache.js",
      "test_opts.js",
      "Face_Biometric/",
      ".lighthouseci/",
      ".playwright-mcp/",
      ".stryker-tmp/",
      "coverage/",
      "test-results/",
      ".tools/",
    ],
  },
];
