name: Knip

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "package-lock.json"
      - ".tools/Developer_Toolkit/knip.json"
      - "**/*.js"
      - "**/*.mjs"
      - "**/*.cjs"
      - "**/*.html"

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Knip report
        uses: codex-/knip-reporter@7ee82434e4adcb560038aaa59bc647fe8c3c6ee4 # v4.0.0
        with:
          command_script_name: knip
          ignore_results: true
          annotations: true
          collapse_sections: auto
